version: 0.2
 
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update
      - echo Installing hugo
      - curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.deb
      - dpkg -i hugo.deb
  pre_build:
    commands:
      - echo In pre_build phase..
      - echo Current directory is $CODEBUILD_SRC_DIR
      - ls -la
      - chmod ugo+x ./pre-build.sh
      - ./pre-build.sh s3://$DEPLOY_S3_BUCKET/yaml
  build:
    commands:
      - chmod ugo+x ./buildhugo.sh
      - ./buildhugo.sh
      - echo "S3 Upload Beginning"
      - aws s3 sync public/ s3://$DEPLOY_S3_BUCKET/ --region ap-southeast-2 --delete --exclude  "video/*"
      - echo "S3 Upload Complete"
      - aws s3api put-object-acl --bucket virtual-aiml-loft-site --key yaml/apj_aiml_loft_workshop.yml --acl public-read
      - aws s3api put-object-acl --bucket virtual-aiml-loft-site --key yaml/fraud-detector-workshop.yaml --acl public-read
      - echo "S3 CF Templates Made Public"
artifacts:
  files:
    - '**/*'
  base-directory: public